### ISSUE TITLE
Incompatibility with "Snow! Real Magic"

### ISSUE THREAD

**Issue by ThisAlbino** [nvb-uy/sod-fabric#1]
I've tried placing patches of every type and they will not work. Tried snow layers and they work fine. Every other block in the mod works.

**Comment by nvb-uy** [comment]
Not enough information, can't reproduce the bug.

Do you have any mod(s) installed? Is this issue in a server, in singleplayer, or both?

-------- Mensaje original --------

**Comment by nvb-uy** [comment]
No more response, closing issue. Reopen if problem persists.

**Comment by ThisAlbino** [comment]
I did a few tests and there seems to be a conflict with Snow! Real Magic!

**Comment by nvb-uy** [comment]
Ah, seems like that mod mixins Minecraft's snowblock itself so that's why it's causing problems. I'll look into an alternative for the future (Like making the block from scratch instead of extending the vanilla class). So I'll start working on it when I got time ! ^^

**Comment by LessThanBenji** [comment]
Hi, this is a really cool mod, but unfortunately i'm using it alongside Snow! Real Magic by Snownee and this particular issue still persists. I don't suppose there's still a fix in the works at all? Not a problem at all if not :)

**Comment by nvb-uy** [comment]
This is fixed on the latest version, are you sure you're on the latest?

**Comment by LessThanBenji** [comment]
Ah, no, I'm using the Modrinth App on which the latest version of Grass Overhaul available is 23.06.09 (I'm playing in 1.20.1 on Fabric 0.15.6). I've just checked the CurseForge page and seen 23.10.11, where I can see your note in the changelog for having fixed this incompatibility. I'll pinch the updated .jar from there and bring it over to Modrinth :)

(PS. I think you've accidentally mislabelled the .jar for *23*.10.11 on Fabric/Quilt on CurseForge as *22*.10.11 -- or at least I'm assuming given the prior versions are ascending under "23").

**Comment by nvb-uy** [comment]
Yup! I mislabeled it haha, I uploaded the fixed version to modrinth too! Thanks for letting me know

**Comment by vinnyg0621** [comment]
um, excuse me...? it's still not fixed on the forge version yet.
![2024-07-07_17 11 30](https://github.com/nvb-uy/Grass-Overhaul/assets/57818441/4f3ca182-85e1-435d-9bf8-1d8cd761c9b4)

**Comment by vinnyg0621** [comment]
problem still persists!

**Comment by vinnyg0621** [comment]
PLEASE FIX IT!!!!!!
